// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJtuKdwL7gouQLyaNG4eROkF4zIR9MMdU',
    appId: '1:159286865034:web:ab437d3f597e43932f9173',
    messagingSenderId: '159286865034',
    projectId: 'fir-auth-v1-sucalit',
    authDomain: 'fir-auth-v1-sucalit.firebaseapp.com',
    storageBucket: 'fir-auth-v1-sucalit.appspot.com',
    measurementId: 'G-GF4X82T07B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPJpbYubH-fU_n3v1N6XniZK3BNMtZ5iw',
    appId: '1:159286865034:android:631f3e391c3f429e2f9173',
    messagingSenderId: '159286865034',
    projectId: 'fir-auth-v1-sucalit',
    storageBucket: 'fir-auth-v1-sucalit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuUR7FgurJCA1l-FhwTa91dSoGQNth8wk',
    appId: '1:159286865034:ios:47293543952cb4eb2f9173',
    messagingSenderId: '159286865034',
    projectId: 'fir-auth-v1-sucalit',
    storageBucket: 'fir-auth-v1-sucalit.appspot.com',
    iosBundleId: 'com.example.firebaseAuthV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuUR7FgurJCA1l-FhwTa91dSoGQNth8wk',
    appId: '1:159286865034:ios:47293543952cb4eb2f9173',
    messagingSenderId: '159286865034',
    projectId: 'fir-auth-v1-sucalit',
    storageBucket: 'fir-auth-v1-sucalit.appspot.com',
    iosBundleId: 'com.example.firebaseAuthV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJtuKdwL7gouQLyaNG4eROkF4zIR9MMdU',
    appId: '1:159286865034:web:0f3504b78c0c81982f9173',
    messagingSenderId: '159286865034',
    projectId: 'fir-auth-v1-sucalit',
    authDomain: 'fir-auth-v1-sucalit.firebaseapp.com',
    storageBucket: 'fir-auth-v1-sucalit.appspot.com',
    measurementId: 'G-03FZD4G1GR',
  );
}
